[package]
name = "font-builder"
version = "0.3.0-beta.1"
authors = ["Rhys Holloway <rhyswilliamholloway@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

### Font specifications

firecore-font-lib = { git = "https://github.com/DoNotDoughnut/firecore-font-lib" }

### Serialization

serde = { version = "1.0", features = ["derive"] }
bincode = "1.3"
ron = "0.6"