[package]
name = "firecore-font-builder"
version = "0.0.2"
authors = ["Rhys H <donotdoughnut99@gmail.com>"]
edition = "2018"

[dependencies]
serde = { version = "1", features = ["derive"] } 
ron = "0.7"
